#include "unit.h"

void TestStrtoi(void) {
	char* p;
	int ret = 0;
	char* str = NULL;
	int i = 0;
	printf("Strtoi Testing\n\n");
	printf("Check Correct Values:\n\n");
	str = "-2147483647";
	i = strtoi(str, &p, &ret);
	printf(" String: %s\nOutput Value: %d    ret: %d\n", str, i, ret);
	str = "-43216";
	i = strtoi(str, &p, &ret);
	printf(" String: %s\nOutput Value: %d    ret: %d\n", str, i, ret);
	str = "Ax127";
	i = strtoi(str, &p, &ret);
	printf(" String: %s\nOutput Value: %d    ret: %d\n", str, i, ret);
	str = "-CxBBABAB12";
	i = strtoi(str, &p, &ret);
	printf(" String: %s\nOutput Value: %d    ret: %d\n", str, i, ret);
	str = "Gx10F";
	i = strtoi(str, &p, &ret);
	printf(" String: %s\nOutput Value: %d    ret: %d\n", str, i, ret);
	str = "-4x1233210";
	i = strtoi(str, &p, &ret);
	printf(" String: %s\nOutput Value: %d    ret: %d\n", str, i, ret);
	str = "!xZOV";
	i = strtoi(str, &p, &ret);
	printf(" String: %s\nOutput Value: %d    ret: %d\n", str, i, ret);

	printf("=================================================\n");
	printf("Check Uncorrect Values:\n\n");
	str = "1234    12345432";
	i = strtoi(str, &p, &ret);
	printf(" String: %s\nOutput Value: %d    ret: %d    p: %s \n", str, i, ret, p);
	str = "2x1000210";
	i = strtoi(str, &p, &ret);
	printf(" String: %s\nOutput Value: %d    ret: %d    p: %s\n", str, i, ret, p);
	str = "Bx32F8";
	i = strtoi(str, &p, &ret);
	printf(" String: %s\nOutput Value: %d    ret: %d    p: %s\n", str, i, ret, p);
	str = "----+++---+--Gx16";
	i = strtoi(str, &p, &ret);
	printf(" String: %s\nOutput Value: %d    ret: %d    p: %s\n", str, i, ret, p);
	str = "+:;x17";
	i = strtoi(str, &p, &ret);
	printf(" String: %s\nOutput Value: %d    ret: %d    p: %s\n", str, i, ret, p);
	str = "xyz"; 
	i = strtoi(str, &p, &ret);
	printf(" String: %s\nOutput Value: %d    ret: %d    p: %s\n", str, i, ret, p); 
	str = "-681fd1";
	i = strtoi(str, &p, &ret);
	printf(" String: %s\nOutput Value: %d    ret: %d    p: %s\n", str, i, ret, p);
	str = "zzzzzzzxzzzzzz";
	i = strtoi(str, &p, &ret);
	printf(" String: %s\nOutput Value: %d    ret: %d    p: %s\n", str, i, ret, p);
	str = "1x00";
	i = strtoi(str, &p, &ret);
	printf(" String: %s\nOutput Value: %d    ret: %d    p: %s\n", str, i, ret, p);
	printf("=================================================\n");
	printf("Check OverFlow Values\n\n");
	str = "2147483650";
	i = strtoi(str, &p, &ret); 
	printf(" String: %s\nOutput Value: %d    ret: %d\n", str, i, ret);
	str = "-2147483650";
	i = strtoi(str, &p, &ret); 
	printf(" String: %s\nOutput Value: %d    ret: %d\n", str, i, ret);
	str = "21474836500000000000000000000000000000000";
	i = strtoi(str, &p, &ret);
	printf(" String: %s\nOutput Value: %d    ret: %d\n", str, i, ret);
	str = "2x11111111111111111111111111111111";
	i = strtoi(str, &p, &ret); 
	printf(" String: %s\nOutput Value: %d    ret: %d\n", str, i, ret);
	str = "!xzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz";
	i = strtoi(str, &p, &ret); 
	printf(" String: %s\nOutput Value: %d    ret: %d\n", str, i, ret);
	str = "Hx11GGGGG3456789098765432345678987654322222222222";
	i = strtoi(str, &p, &ret); 
	printf(" String: %s\nOutput Value: %d    ret: %d\n", str, i, ret);
	str = "9999999999999999999999999999999";
	i = strtoi(str, &p, &ret); 
	printf(" String: %s\nOutput Value: %d    ret: %d\n\n", str, i, ret);
}

void TestItoa(void) {
	int bufSize = 33;
	char* buf = NULL;
	int value = 2147483647;
	int cc = 2;
	int i = 0;
	printf("Itoa Testing\n\n");
	i = my_itoa(buf, bufSize, value, cc);
	printf(" Value: %d\nOutput Value: %d    Buffer: %s\n", value, i, buf);
	buf = (char*)malloc(bufSize * sizeof(char));
	if (!buf)
		return;
	value = -2147483647 - 1;
	cc = 2;
	i = my_itoa(buf, bufSize, value, cc);
	printf(" Value: %d\nOutput Value: %d    Buffer: %s\n", value, i, buf);
	value = 52;
	cc = 62;
	i = my_itoa(buf, bufSize, value, cc);
	printf(" Value: %d\nOutput Value: %d    Buffer: %s\n", value, i, buf);
	value = 100;
	cc = 16;
	i = my_itoa(buf, bufSize, value, cc);
	printf(" Value: %d\nOutput Value: %d    Buffer: %s\n", value, i, buf);
	value = 1149;
	cc = 23;
	i = my_itoa(buf, bufSize, value, cc);
	printf(" Value: %d\nOutput Value: %d    Buffer: %s\n", value, i, buf);
	value = -602001;
	cc = 45;
	i = my_itoa(buf, bufSize, value, cc);
	printf(" Value: %d\nOutput Value: %d    Buffer: %s\n", value, i, buf);
	value = 1348431647;
	cc = 36;
	i = my_itoa(buf, bufSize, value, cc);
	printf(" Value: %d\nOutput Value: %d    Buffer: %s\n", value, i, buf);
}